worker_processes auto;
error_log /dev/null;
pid /tmp/nginx.pid;

events {
    worker_connections 4096;
    multi_accept on;
}

http {
    access_log off;

    upstream backend {
        server backend:19876;
        keepalive 128;
    }

    server {
        listen 8199;
        server_name _;

        location / {
            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
        }
    }
}
