apiVersion: v1
kind: Service
metadata:
  name: {{ include "dwaar-ingress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dwaar-ingress.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "dwaar-ingress.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: 80
      protocol: TCP
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: 443
      protocol: TCP
